### ISSUE TITLE
Thread Priority Problem

### ISSUE THREAD

**Issue by gameplayoffert** [PotatoMaster101/se4#1]
hi, i have compiled your project but it doesn't work when i run. The thread is not found. I have tried to change the code and it worked. The "thread priority" for dx12 is "2" and for the dx11 is "6" but for me when i use the "dx11" it's not "6" but "2" so a little bit strange.

**Comment by gameplayoffert** [comment]
you can solve the issue when you have read

**Comment by PotatoMaster101** [comment]
I will have a look but need to download the game again first. Possibly changed due to game update.
