### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CinderFox101** [PotatoMaster101/se4#3]
what if there IS an error... like...

ERROR: Game thread not found

**Comment by PotatoMaster101** [comment]
What DX version are you running? DX11 or DX12?
Check game process name `SniperElite4_DXxx.exe`

**Comment by CinderFox101** [comment]
im stupid i need a clear tutorial on how to do it, i know literally nothing on how to do it or where to start

**Comment by PotatoMaster101** [comment]
**Check DX Version**:
1. Run Sniper Elite 4
2. Open Task Manager (CTRL + ALT + DEL)
3. Find the game in Task Manager, it will be called `SniperElite4_DX11.exe` or `SniperElite4_DX12.exe`

I have tested the cheat on my PC under DX11 and DX12 mode and they are working fine.

**Comment by PotatoMaster101** [comment]
~~If the cheat is still not working, try using the 1.0.0 version instead of 1.0.1.~~
I have released a new version 1.0.2 which include a potential fix for this issue.

**Comment by CinderFox101** [comment]
all i have to do is download the .exe and run it after starting the game or is there more shit to do?

**Comment by PotatoMaster101** [comment]
Download .exe after starting the game or download source file and build the .exe then run it after game start
